---

- hosts: kube-masters
  gather_facts: false
  tasks: 
    - name: Clone Demo Project
      shell: "git clone https://github.com/ichbinblau/SmartHome-Demo.git"
    - name: Checkout Kubernetes Branch
      shell: "git checkout k8s"
    - name: Create directory for local repository
      shell: "sudo mkdir -p /var/lib/registry"
    - name: Tell Docker to setup local registry
      shell: "sudo docker run -d -p 5000:5000 --restart=always --name registry -v /var/lib/registry:/var/lib/registry registry:2"
    - name: Create K8 namespace for demo
      shell: "kubectl create ns iot2cloud"
    - name: Assign labels to nodes    
      command: "kubectl label nodes {{ item.node }} platform={{ item.label }} -n iot2cloud"
      with_items:
        - { node: 'gateway1', label: 'minnowboard' }
        - { node: 'gateway2', label: 'minnowboard' }
        - { node: 'gateway3', label: 'minnowboard' }
     - name: Create a database secret password
       shell: "echo -n $MYSQL_ROOT_PASS > mysql_root_pass.secret"
     - name: Create database password 
       shell: "kubectl -n iot2cloud create secret generic mysql-root-pass --from-file=mysql-root-pass.secret"
     - name: Create database pod
       command: "kubectl -n iot2cloud -f /home/demouser/SmartHome-Demo/smarthome-web-portal/tools/yamls/{{ item }}"
       with_items: 
         - 'mariadb-master-service.yaml' 
         - 'mariadb-master.yaml'
         - 'mariadb-slave-service.yaml'
         - 'mariadb-slave.yaml'
     - name: Set up RabbitMQ
       command: "kubectl -n iot2cloud -f /home/demouser/SmartHome-Demo/smarthome-web-portal/tools/yamls/{{ item }}"`
       with_items:
         - 'rabbitmq-service.yaml'
         - 'rabbitmq.yaml'
     - name: Create IoT Rest API Service and Gateway Server
       command: "kubectl -n iot2cloud -f /home/demouser/SmartHome-Demo/smarthome-web-portal/tools/yamls/{{ item }}"`
       with_items:
         - 'smarthome-gateway-service.yaml'
         - 'smarthome-gateway.yaml'
     - name: Setup Home Dashboard 
       command: "kubectl -n iot2cloud -f /home/demouser/SmartHome-Demo/smarthome-web-portal/tools/yamls/{{ item }}"`
       with_items:
         - 'home-portal-service.yaml'
         - 'home-portal.yaml'
    - name: Setup Admin Portal
       command: "kubectl -n iot2cloud -f /home/demouser/SmartHome-Demo/smarthome-web-portal/tools/yamls/{{ item }}"`
       with_items:
         - 'admin-portal-service.yaml'
         - 'admin-portal.yaml'
    - name: Setup Celery Worker
       command: "kubectl -n iot2cloud -f /home/demouser/SmartHome-Demo/smarthome-web-portal/tools/yamls/{{ item }}"`
       with_items:
         - 'celery-worker.yaml'
    - name: pull an image
