---

- name: Enable iptables [RedHat]
  blockinfile:
    dest: /etc/sysctl.conf
    state: present
    create: yes
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  become: True
  when:
      - ansible_os_family == 'RedHat'

- name: Reload sysctl [RedHat]
  command: sysctl -p
  become: True
  when:
      - ansible_os_family == 'RedHat'

- name: Kubeadm init
  become: True
  command: kubeadm init --pod-network-cidr="{{ pod_cidr }}" --service-cidr="{{ service_cidr }}" --token {{ token }} --apiserver-advertise-address={{ api_advertise_ip }}
  register: kubeadm_init_out


- name: Log Kubeadm init
  debug: msg="{{ kubeadm_init_out }}"

- name: Creates directory
  file: path=.kube state=directory


# Note ansible `copy` doesn't work here because of root privilege required for /etc
-  name: Copy admin.conf to ~/.kube/config
   command: cp /etc/kubernetes/admin.conf /home/{{ username }}/.kube/config
   become: True

- name: Chown .kube/config
  become: True
  command: chown -R {{ username }}:{{ username }} /home/{{ username }}/.kube/

# RBAC

- name: Copy RBAC file
  template:
    src: rbac.yml
    dest: /tmp/rbac.yml
    mode: 0644

- name: Override default RBAC settings
  become: True
  become_user: "{{ username }}"
  command: kubectl replace -f /tmp/rbac.yml

- name: Remove master taint
  become: True
  become_user: "{{ username }}"
  command: kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/master-

# Helm
- name: Download Helm setup script with +x permission
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
    dest: /tmp/get_helm.sh
    mode: 0777

- name: Install Helm
  command: /tmp/get_helm.sh

- name: Run Helm Init
  become: True
  become_user: "{{ username }}"
  command: helm init
