---

- include: iptables.yml
- include: kubeadm-init.yml
- include: rbac.yml
- include: helm.yml

# Networking overlay
- include: canal.yml
  when: network_driver == 'canal'
- include: weave.yml
  when: network_driver == 'weave'
