---

# Kolla-Kubernetes Configuration

# Note: Ansible remote-src copy does not recurse dirs, hence using cp
- name: Copy default kolla configuration to etc
  become: True
  command: cp -aR /home/{{ username }}/kolla-ansible/etc/kolla /etc

- name: Copy default kolla-kubernetes configuration to /etc
  become: True
  command: cp -aR /home/{{ username }}/kolla-kubernetes/etc/kolla-kubernetes /etc

- name: Generate default passwords via SPRNG
  command: kolla-kubernetes-genpwd

# TODO Remove ignore errors
- name: Create a kubernetes namespace to isolate this kolla deployment
  command: kubectl create namespace kolla
  ignore_errors: True

# TODO move to node also
#- name: Label the AIO node as the compute and controller node:
#  kubectl label node $(hostname) kolla_compute=true
#  kubectl label node $(hostname) kolla_controller=true

# TODO Remove ignore errors
- name: Label the master node as the controller node
  command: kubectl label node {{ ansible_hostname }} kolla_controller=true
  ignore_errors: True

# TODO Remove ignore errors
- name: Label the master node a compute node
  command: kubectl label node {{ ansible_hostname }} kolla_compute=true
  ignore_errors: True
  when:
    - master_works == True

# TODO implement
#- name: Modify kolla configuration
#set network_interface in /etc/kolla/globals.yaml to the management interface name.
#set neutron_external_interface in /etc/kolla/globals.yml to the Neutron interface name.
#This is the external interface that neutron will use.  It must not have an IP
#address assigned to it.

- set_fact:
      globals_config: "{{ lookup('template', 'templates/globals_config.j2') }}"

- name: Add required configuration to the end of /etc/kolla/globals.yml
  blockinfile:
    dest: /etc/kolla/globals.yml
    content: '{{ globals_config }}'
    state: present
    insertafter: EOF

- name: Make /etc/kolla/config
  become: True
  command: mkdir -p /etc/kolla/config/

- name: Enable QEMU libvirt functionality and enable a workaround for a bug in libvirt
  blockinfile:
    dest: /etc/kolla/config/nova.conf
    state: present
    create: yes
    content: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
  become: True

- name: Generate the default configuration
  command: sudo ansible-playbook -e ansible_python_interpreter=/usr/bin/python -e @/etc/kolla/globals.yml -e @/etc/kolla/passwords.yml -e CONFIG_DIR=/etc/kolla kolla-kubernetes/ansible/site.yml

# TODO remove ignore errors
- name: Generate the Kubernetes secrets and register them with Kubernetes
  command: /home/{{ username }}/kolla-kubernetes/tools/secret-generator.py create
  ignore_errors: True

# TODO remove ignore errors currently needed for re-running task
- name: Enable resolv.conf workaround
  command: /home/{{ username }}/kolla-kubernetes/tools/setup-resolv-conf.sh kolla
  ignore_errors: True